#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_base(
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_HOME, KC_TAB,
        KC_Q, KC_TAB, KC_Q, KC_W, KC_C, KC_F, KC_D, KC_P, KC_H, KC_J, KC_K, KC_LBRC, KC_RBRC, KC_END, KC_MPLY, KC_CAPS,
        KC_CAPS, KC_L, KC_A, KC_S, KC_R, KC_T, KC_G, KC_Y, KC_N, KC_E, KC_O, KC_ENT, KC_PGUP, KC_MUTE, KC_LSFT, KC_I,
        KC_X, KC_V, KC_M, KC_U, KC_Z, KC_B, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP, KC_PGDN, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,
        KC_RALT, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT,
    ),
    [1] = LAYOUT_base(
        KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_MINS, KC_EQL, KC_DEL, KC_HOME, KC_TAB,
        KC_Q, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_BSLS, KC_END, KC_MPLY, KC_CAPS,
        KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_ENT, KC_PGUP, KC_MUTE, KC_LSFT, KC_MINS,
        KC_PLUS, KC_EQL, KC_NO, KC_NO, KC_NO, KC_NO, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP, KC_PGDN, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,
        KC_RALT, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT,
    ),
};
