[ids]
*

[main]
q = q
w = w
e = c
r = f
t = d
y = p
u = h
i = j
o = k
p = l
leftbrace = apostrophe
rightbrace = semicolon
a = a
s = s
d = r
f = t
g = g
h = y
j = n
k = e
l = o
semicolon = i
apostrophe = slash
z = x
x = v
c = m
v = u
b = z
n = b
m = comma
comma = dot
dot = rightbrace
slash = leftbrace
